# Generated by Django 5.1.7 on 2025-04-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los_cosiacos', '0004_alter_cosiaco_creador_opinion_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosiaco',
            name='categoria',
            field=models.ManyToManyField(to='los_cosiacos.categoria', verbose_name='categoria'),
        ),
    ]
