# Generated by Django 5.1.7 on 2025-04-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los_cosiacos', '0007_alter_opinion_cosiaco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
    ]
