# Generated by Django 5.1.7 on 2025-04-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('los_cosiacos', '0008_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosiaco',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
    ]
